### ISSUE TITLE
v1.5.0 - Current Round & Categories

### ISSUE THREAD

**Issue by outtahere** [andybotting/xbmc-addon-afl-video#14]
A couple of things noticable since kodi prompted for v1.5.0 update:
'Current Round' is obsolete for 2015 season, should only be in 2016 (remove id from config.py)
'Editorial Highlights', 'Media Conferences' & 'News' are all being populated and should be included in config.py (doubtful 'Access All Areas' will be making a return given the circumstances)
HTH

**Comment by andybotting** [comment]
Good pickup. I was thinking of removing the 'Current Round' altogether - it often doesn't work once you get to Monday or Tuesday and it's already looking to the next weekend.

Regarding 'Editorial Highlights', 'Media Conferences' & 'News': where are these being populated? The old 'channels' don't work using the old streaming method that we used to use.

**Comment by outtahere** [comment]
Yes I get that the Current Round can be fubared by midweek, but by midseason I can never remember the current round number anyway and find it convenient.

The categories are being populated at http://www.afl.com.au/video/ and curl returns the category meta tags from the url's:
```
<meta name="omni-video-program-category" content="News">
<meta name="omni-video-program-category" content="Media Conferences">
<meta name="omni-video-program-category" content="Editorial Highlights">
```

They provide all I need.
News provides: Daily Footy Feed, Fantasy Previews and some club specific stuff like SwansTV
Media Conferences provides: All Coach post game interviews (currently NAB Cup)
Editorial Highlights provides: Specialised or exclusive content, currently a look at GWS pre-season

Running Kodi 15.2 on Linux, I add these categories to ~/.kodi/addons/plugin.video.afl-video/resources/lib/config.py
It's a 'must have' add-on for me, so thanks for all your hard work in creating and maintaining it.

**Comment by andybotting** [comment]
Interesting. Can you provide a pull request or a code example?

**Comment by andybotting** [comment]
I've been looking at reverse engineering the the feed from the offical AFL app, but it's going to take a while. Once that's done, we should have a full selection of videos

**Comment by outtahere** [comment]
~/.kodi/addons/plugin.video.afl-video/resources/lib/config.py
```

---- snip ----

# Categories existing on the new content system
CATEGORIES = [
    'Match Replays 2016',
    'Match Replays 2015',
    'Match Replays 2014',
    'Match Replays 2013',
    #'Club Video',
    'Editorial Highlights',
    'Media Conferences',
    'News',
    'Settings'
]

---- snip ----
```

**Comment by andybotting** [comment]
Will be fixed in a new version
