### ISSUE TITLE
Support downloads

### ISSUE THREAD

**Issue by sfatula** [andybotting/xbmc-addon-afl-video#2527]
Instead of just replaying a game, you should allow them to download to the local machine. This allows one with a slower connection to download all night if they have to, and therefore, play at "full speed" once downloaded.

**Comment by andybotting** [comment]
We already break terms and conditions to serve these streams, so allowing users to download the video I suspect would be a step too far. I know that ABC took down a project like this for a similar reason, so we try and stay under the radar.

Having said that, you can find the URL of the video from the Kodi log file after you begin to stream a match replay, and I have used this to then download the whole video.
