### ISSUE TITLE
Live Matches not showing up

### ISSUE THREAD

**Issue by pcwizard7** [andybotting/xbmc-addon-afl-video#2650]
User Type: Telstra (Free)
Addon version: Lastest Stable release 

In the live matches, it shows all upcoming matches for the week but when a match is set to go live it just disappears from the list, and there no option to watch it?

thanks

**Comment by andybotting** [comment]
Unfortunately no. Telstra no longer provide access to any live matches, so we no longer can provide them through the add-on.

Telstra now say you should use Kayo.

Here's a little background info: https://exchange.telstra.com.au/were-evolving-the-way-we-deliver-live-afl-and-nrl-games/

cheers
