### ISSUE TITLE
Not sure how... 

### ISSUE THREAD

**Issue by parallelandy** [andybotting/xbmc-addon-afl-video#2651]
Hi Glennguy

Not sure how to message you directly.

How is the AFL add on still working?

I don't have free to air TV and rely on Kayo however the game is not live there. 

Only option was to try Kodi. Somehow this is still working even though Live Pass is no longer current. 

So thankful it's working however I can't understand how. 

Very happy. 

Andy

**Comment by andybotting** [comment]
Hey @parallelandy 

So we no longer have access to the live matches in the add-on as Telstra don't support it anymore. They've instructed their customers to move to Kayo, so that's really your only option right now.

cheers

**Comment by parallelandy** [comment]
Hi @andybotting

I am watching it on Kodi right now. That's what doesn't make sense.

**Comment by andybotting** [comment]
Yeah, you're right. I just opened it up through the AFL app and it's there too. I would expect that this isn't the norm and they've just decided to show the GF maybe?

**Comment by parallelandy** [comment]
Wow it is too! They must have got a lot of complaints because this was not announced anywhere. Thanks for replying :-)
