### ISSUE TITLE
AFL live TV not working

### ISSUE THREAD

**Issue by sdmcintyre** [andybotting/xbmc-addon-afl-video#347]
Hi Andy,

I have put in my details for the AFL live pass, but the live TV is not working.  I get the "AFL live pass subscription has expired". This isn't true since it works fine on my android tablet.

I have been looking at the source and trying the APIs out in postman and it looks like this endpoint may have changed?
https://api.afl.com.au/cfs/users/session/subscriptions?sessionId={id}

I get this response in postman with a valid session id:

{
  "code": "CFSUSERS001",
  "techMessage": "Login session token or ip is invalid",
  "userMessage": "Sorry, there has been an error processing your request, please try again.",
  "host": "rlhay9mwcmis03",
  "date": "2017-01-04T11:45:37.337+0000",
  "version": "4.0.13",
  "mdc": "@0464@"
}

Thanks,
Stuart

**Comment by glennguy** [comment]
Hi Stuart,

Working fine here - are you behind a VPN?

**Comment by andybotting** [comment]
We've just released v1.7.0 with fixes for 2017 season and Live Pass. Try it out and let us know how it goes.

cheers,
Andy
