### ISSUE TITLE
AFL Video Replays not working

### ISSUE THREAD

**Issue by AbsMate** [andybotting/xbmc-addon-afl-video#38]
I've tried playing the replays on my Kodi setup on my computer and also my TV, both of them allow me to play the AFL replays however on my macbook setup, whenever I select a replay it pops up with an error "No videos found, Replays are only available 24-48 hours after match has been played". I'm confused as to whether this is true because my other Kodi setups work perfectly fine more than 48 hours after a match has been played. I've already tried restarting my computer and also uninstalling/reinstalling the addon itself.

Any help would be greatly appreciated

**Comment by andybotting** [comment]
I think a copy of your full log file might help here. Install the Kodi Log Uploader (from Program add-ons) and send me the link it gives you.

cheers

**Comment by AbsMate** [comment]
Ok so that's done here's what it says:
Uploaded with ID: pdfs2ugre
URL: http://xbmclogs.com/pdfs2ugre

Thank you Andy

**Comment by AbsMate** [comment]
Sorry Andy that link was not right this is it:
http://xbmclogs.com/purx1yqwv

**Comment by andybotting** [comment]
I managed to finally replicate the issue, and I've pushed a fix in v1.6.1 which is now in the Catchup TV AU repository. Can you let me know if that fixes it for you?

**Comment by AbsMate** [comment]
Andy you're a legend mate it's working perfectly now, thankyou for
responding so quickly appreciate the help :)

**Comment by andybotting** [comment]
Great news. Go Cats ;)
