### ISSUE TITLE
Cant get video to play in 1.3.1

### ISSUE THREAD

**Issue by widgzcaf** [andybotting/xbmc-addon-afl-video#4]
Hi Andy, first great job with this plugin.

I just have a problem where match replays wont play with version 1.3.1.  The addon can see the correct game listings but when trying to play the video nothing happens - no errors just stays on the screen listing quarter 1,2,3,4 etc.

Any ideas.  I have xbmx.log if I can figure out how to upload it

**Comment by andybotting** [comment]
I'm hoping this is fixed in newer releases. Please open again if not.
