### ISSUE TITLE
Match replays do not load

### ISSUE THREAD

**Issue by GhostAway** [andybotting/xbmc-addon-afl-video#40]
Hey,

i downloaded the AFL video add on and i've tried to watch replays of matches and they just don't load.

i get a quick 'working' signal at the bottom and then it just stops. The preseason games seem to work.

**Comment by andybotting** [comment]
Please send me a copy of your log file

**Comment by GhostAway** [comment]
where do i find that?

**Comment by andybotting** [comment]
Install the Kodi Log Uploader (from Program add-ons) and send me the link it gives you.

Can you confirm you're using version 1.6.1?

**Comment by GhostAway** [comment]
i am currently using 1.6.1, i'll grab that link for you.

**Comment by GhostAway** [comment]
all my add on sections are empty for some reason
