### ISSUE TITLE
AFL Video - Access to Match Replays

### ISSUE THREAD

**Issue by BB888** [andybotting/xbmc-addon-afl-video#5]
I just installed the AFL Video addon from the AU Catch-up TV repo.

I have an afltv.com.au subscription and have been using the web interface to watch match replays, but I was keen to use your addon as it would be a cleaner approach.  i have an International subscription and reside outside Australia.

I couldn't find anywhere to enter my subscription details, the settings tab had only connection speed and favorite team.

The addon works fine for free content, but I cant figure out how to access match replays (which requires a subscription, which I have).

How do I complete the setup to enable match replay videos?

Below is a portion of the xbmc.log;
...
16:07:58 T:2340  NOTICE: Starting XBMC (12.3 Git:20131212-9ed3e58), Platform: Windows 8 64-bit, build 9200. Built on Dec 19 2013 (compiler 1600)
...
16:08:05 T:4028  NOTICE: [AFL Video v1.3.1] Initialised
16:08:05 T:4940  NOTICE: Thread Background Loader start, auto delete: false
16:08:09 T:7944  NOTICE: Thread XBPyThread start, auto delete: false
16:08:10 T:7944  NOTICE: -->Python Interpreter Initialized<--
16:08:10 T:7944  NOTICE: [AFL Video v1.3.1] Initialised
16:08:10 T:488  NOTICE: Thread Background Loader start, auto delete: false
16:08:15 T:4264  NOTICE: Thread XBPyThread start, auto delete: false
16:08:15 T:4264  NOTICE: -->Python Interpreter Initialized<--
16:08:15 T:4264  NOTICE: [AFL Video v1.3.1] Initialised
16:08:15 T:4264  NOTICE: [AFL Video v1.3.1] Fetching match list for round CD_R201401411...
16:08:15 T:4264  NOTICE: [AFL Video v1.3.1] Fetching URL: http://www.afl.com.au/api/gas/afl/roundVideo/CD_R201401411
16:08:26 T:4264   ERROR: C:\Users...\AppData\Roaming\XBMC\addons\plugin.video.afl-video\resources\lib\comm.py:249: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
                                              matches = rnd.find('matches').getchildren()
16:08:26 T:4264  NOTICE: [AFL Video v1.3.1] Found 9 matches
16:08:26 T:7324  NOTICE: Thread Background Loader start, auto delete: false
16:08:30 T:1468  NOTICE: Thread XBPyThread start, auto delete: false
16:08:30 T:1468  NOTICE: -->Python Interpreter Initialized<--
16:08:31 T:1468  NOTICE: [AFL Video v1.3.1] Initialised
16:08:31 T:1468  NOTICE: [AFL Video v1.3.1] Fetching video list for CD_M20140141105...
16:08:31 T:1468  NOTICE: [AFL Video v1.3.1] Fetching URL: http://www.afl.com.au/api/gas/afl/roundVideo/CD_R201401411
16:08:41 T:1468   ERROR: C:\Users...\AppData\Roaming\XBMC\addons\plugin.video.afl-video\resources\lib\comm.py:283: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
                                              for qtr in periods.getchildren():
16:08:41 T:7048  NOTICE: Thread Background Loader start, auto delete: false
16:08:51 T:2340  NOTICE: DVDPlayer: Opening: http://bponlinewoc6264.ngcdn.telstra.com/platform_release_geo/content/671/35/ESS_V_RICH_RD11_Q1_S_2752389856__164960.mp4?start=0
16:08:51 T:2340 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:08:51 T:3736  NOTICE: Thread CDVDPlayer start, auto delete: false
16:08:51 T:3736  NOTICE: Creating InputStream
16:08:53 T:3736 WARNING: XFILE::CCurlFile::CReadState::FillBuffer: curl failed with code 22
16:08:53 T:3736 WARNING: XFILE::CCurlFile::CReadState::FillBuffer: Reconnect, (re)try 1
16:08:53 T:3736 WARNING: XFILE::CCurlFile::CReadState::FillBuffer: curl failed with code 22
16:08:53 T:3736   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
16:08:53 T:3736   ERROR: XFILE::CFileCache::Open - failed to open source http://bponlinewoc6264.ngcdn.telstra.com/platform_release_geo/content/671/35/ESS_V_RICH_RD11_Q1_S_2752389856__164960.mp4?start=0
16:08:53 T:3736   ERROR: CDVDPlayer::OpenInputStream - error opening [http://bponlinewoc6264.ngcdn.telstra.com/platform_release_geo/content/671/35/ESS_V_RICH_RD11_Q1_S_2752389856__164960.mp4?start=0]
16:08:53 T:3736  NOTICE: CDVDPlayer::OnExit()
16:08:53 T:3736  NOTICE: CDVDPlayer::OnExit() deleting input stream
16:08:53 T:2340   ERROR: Playlist Player: skipping unplayable item: 0, path [http://bponlinewoc6264.ngcdn.telstra.com/platform_release_geo/content/671/35/ESS_V_RICH_RD11_Q1_S_2752389856__164960.mp4?start=0]
16:08:53 T:6532  NOTICE: Thread Background Loader start, auto delete: false
16:08:53 T:2340  NOTICE: CDVDPlayer::CloseFile()
16:08:53 T:2340 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:08:53 T:2340  NOTICE: DVDPlayer: waiting for threads to exit
16:08:53 T:2340  NOTICE: DVDPlayer: finished waiting
16:08:54 T:2292  NOTICE: PrimeWire: Playback Stopped
16:08:54 T:2292  NOTICE: PrimeWire: Service: Resetting...
16:09:03 T:2340  NOTICE: Storing total System Uptime
16:09:03 T:2340  NOTICE: Saving settings
16:09:03 T:2340  NOTICE: stop all
...

**Comment by andybotting** [comment]
We're now supporting AFL live pass subscription for live video, although currently broken, will be fixed soon
