### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by mugsyman** [andybotting/xbmc-addon-afl-video#534]
Paid afl live subscription. Unable to sign in to recent update. Asking for mobile not working. Has been perfect on previous versions

**Comment by andybotting** [comment]
Is it a paid subscription, or a free pass from Telstra?

It's currently only working with the Telstra free at the moment.

**Comment by mugsyman** [comment]
Ok. Yes it is paid

**Comment by andybotting** [comment]
Paid subscription now supported!

**Comment by mugsyman** [comment]
Tested. Works great, thanks
