### ISSUE TITLE
new xbmc version

### ISSUE THREAD

**Issue by zoomzoom2005** [andybotting/xbmc-addon-afl-video#6]
Hi Andy,
Great add ons AFL and NRL, problem is new version of xmbc Gotham doe`s not allow you to enable the NRL add on comes up incompatible, any update soon?
cheers 
zoomzoom

**Comment by sytek9** [comment]
Hi Andy,
I have script error on all the add ons under Gotham 13.2, however they all work fine with Kodi, please fix.
regards,
Tom

**Comment by andybotting** [comment]
Log file please
